export const FETCH_PEOPLE_STARTED = 'FETCH_PEOPLE_STARTED';
export const FETCHED_PEOPLE_SUCCESSFULLY = 'FETCHED_PEOPLE_SUCCESSFULLY';
export const ADD_PERSON = 'ADD_PERSON';
export const DELETE_PERSON = 'DELETE_PERSON';
